services:
  postgres:
    image: postgres:16
    container_name: trimo-detail-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: trimo_admin
      POSTGRES_PASSWORD: trimo_dev_2026
      POSTGRES_DB: trimo_detail
    ports:
      - "5433:5432"
    volumes:
      - pgdata_v2:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: trimo-detail-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata_v2: